version: '3'

services:
  django:
    build: ./fampay_task
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fampay_task/:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6381:6381"
  celery:
      build: ./fampay_task
      command: celery -A fampay_task worker -l INFO
      volumes:
        - ./fampay_task/:/usr/src/app
      environment:
        - DEBUG=1
      depends_on:
        - redis
  celery-beat:
      build: ./fampay_task
      command: celery -A fampay_task beat -l INFO
      volumes:
        - ./fampay_task/:/usr/src/app
      environment:
        - DEBUG=1
      depends_on:
        - redis
